### ISSUE TITLE
Problem with logfile timestamp

### ISSUE THREAD

**Issue by philippesamuel** [ex4sperans/mag#6]
While trying to run the iris_example an error occured here:
https://github.com/ex4sperans/maggot/blob/2f93644c666cc195acbb58476b8868429a3e8403/maggot/experiment.py#L231-L236

```python
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\SantoP23\AppData\Local\JetBrains\PyCharm 2021.1\plugins\python\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:\Users\SantoP23\AppData\Local\JetBrains\PyCharm 2021.1\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/SantoP23/Documents/_Current_Projects/_NNProjekt/Philippes_Code/test_maggot/iris_sklearn.py", line 66, in <module>
    main()
  File "C:/Users/SantoP23/Documents/_Current_Projects/_NNProjekt/Philippes_Code/test_maggot/iris_sklearn.py", line 43, in main
    experiment = Experiment(config=svm_config)
  File "c:\users\santop23\documents\_current_projects\_nnprojekt\philippes_code\test_maggot\maggot-master\maggot\experiment.py", line 148, in __init__
    self._setup_log_file()
  File "c:\users\santop23\documents\_current_projects\_nnprojekt\philippes_code\test_maggot\maggot-master\maggot\experiment.py", line 234, in _setup_log_file
    logfile = time.strftime("%Y-%m-%d-%H-%M-%S-%s", time.gmtime())
ValueError: Invalid format string

**Comment by philippesamuel** [comment]
Removing "`-%s`" worked for me.
